packages:
  - apps/*
  - packages/*
  - tools/*

catalogs:
  build:
    vite: npm:@voidzero-dev/vite-plus-core@latest
    vitest: npm:@voidzero-dev/vite-plus-test@latest
    vite-plus: latest
    typescript: ^6.0.3
    "@typescript/native-preview": 7.0.0-dev.20260509.2
  cli:
    bumpp: ^11.1.0
  type:
    "@types/node": ^25.6.2

overrides:
  vite: "catalog:build"
  vitest: "catalog:build"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
