packages:
  - website
  - packages/*

allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  workerd: true

catalogs:
  build:
    '@liangmi/vp-config': ^0.1.2
    '@tsdown/css': ^0.22.0
    '@vitejs/plugin-vue': ^6.0.7
    '@unocss/reset': ^66.7.0
    vite: npm:@voidzero-dev/vite-plus-core@0.2.1
    vite-plus: 0.2.1
    typescript: ^6.0.3
    '@typescript/native-preview': 7.0.0-dev.20260509.2
    unocss: ^66.7.0
    unplugin-vue: ^7.2.0
    void: latest
    vue: ^3.5.35
    '@vueuse/core': ^14.3.0
  cli:
    bumpp: ^11.1.0
    cac: ^7.0.0
    picocolors: ^1.1.1
    '@oxc-node/cli': ^0.1.0
  icon:
    '@iconify-json/ph': ^1.2.2
  type:
    '@types/node': ^25.9.1

minimumReleaseAgeExclude:
  - '@liangmi/vp-config@0.1.2'

overrides:
  vite: 'catalog:build'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
